sample.interval=20000
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"isBaseNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"read.dcf" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".read_description" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"getNamespace" "asNamespace" "getExportedValue" "::" "formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grepl" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "textConnection" "capture.output" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.character" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"character" "vapply" ".rs.asCaseInsensitiveRegex" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"as.environment" "get" "inherits" ".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "lapply" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"isNamespace" "asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"[" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"get" "getExportedValue" "::" "formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"environment" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"environment" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grepl" "ifelse" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"paste" "gsub" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLines" "writeLinesUTF8" "of0" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unlist" "simplify2array" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"psub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLinesUTF8" "of0" "writeHref" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"fsub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "isBlankRd" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"existsInFrame" "<Anonymous>" "lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"fsub" "vhtmlify" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grepl" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lapply" "sapply" "RdTags" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"psub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"%in%" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" "lapply" "sapply" "RdTags" "get_link" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"c" "match" "%in%" "deparse" "eval" "match.arg" "sink" "capture.output" ".rs.getSignature" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lazyLoadDBfetch" "mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"get" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.name" "getNamespace" "asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"getNamespace" "asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"c" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"c" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"c" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" "lapply" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unique" "simplify2array" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "%in%" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"sub" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"psub" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLines" "writeLinesUTF8" "of0" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"mget" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"isBaseNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"FUN" "lapply" "sapply" "RdTags" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" "lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"lazyLoadDBfetch" "get" "inherits" ".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "%in%" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" "lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list.default" "as.list" "lapply" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unlist" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "%in%" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"psub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unlist" "unique" "simplify2array" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "isBlankRd" "writeWrapped" "writeBlock" "writeTabular" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unlist" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "%in%" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"vapply" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list.default" "as.list" "lapply" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLines" "writeLinesUTF8" "of0" "enterPara" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.name" "getNamespace" "asNamespace" "getExportedValue" "::" "formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"get" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"c" "put" "putw" "writeBlock" "Rd2txt" "tryCatchList" "tryCatch" ".Rd_get_text" ".Rd_get_title" "gsub" ".Rd_format_title" "strwrap" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"lapply" "unlist" "apply" "find.package" "index.search" "<Anonymous>" ".rs.getHelp" "<Anonymous>" 
"&" ".rs.startsWith" ".rs.fuzzyMatches" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"get" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list.default" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.character" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"close" "read.dcf" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".read_description" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"unique.default" "unique" "simplify2array" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match" "%in%" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ifelse" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
".External2" "type.convert" "read.table" "read.csv" 
".External2" "type.convert" "read.table" "read.csv" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"unique" "f" "Reduce" ".rs.getCompletionsPackages" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"FUN" "lapply" "Reduce" ".rs.getCompletionsPackages" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"print.default" "print" "print.factor" "print" 
"print.default" "print" "print.factor" "print" 
"print.default" "print" "print.factor" "print" 
"print.default" "print" "print.factor" "print" 
"print.default" "print" "print.factor" "print" 
"print.factor" "print" 
"encodeString" "print.factor" "print" 
"print.factor" "print" 
"encodeString" "print.factor" "print" 
"print.factor" "print" 
"encodeString" "print.factor" "print" 
"encodeString" "print.factor" "print" 
"print.factor" "print" 
"print.factor" "print" 
"print.factor" "print" 
"encodeString" "print.factor" "print" 
"print.factor" "print" 
"print.factor" "print" 
"print.factor" "print" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"sink" "capture.output" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grepl" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"fsub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"htmlify" "isBlankLineRd" "addParaBreaks" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"print.factor" "print" 
"[.data.frame" "[" 
"structure" ".POSIXct" "Sys.time" "srcfilecopy" "parse" "withCallingHandlers" "suppressWarnings" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getAnywhere" ".rs.getCompletionsSingleBracket" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
".rs.getAnywhere" ".rs.getCompletionsSingleBracket" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
".rs.formCompletionVector" ".rs.makeCompletions" ".rs.emptyCompletions" ".rs.getCompletionsSingleBracket" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
".subset2" "<Anonymous>" "[[.data.frame" "[[" "$.data.frame" "$" "find.package" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" "<Anonymous>" 
".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"unique" "setdiff" ".rs.getActiveArgument" ".rs.getCompletionsFunction" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"FUN" "lapply" "sapply" "RdTags" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" "<Anonymous>" 
"[[" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" "<Anonymous>" 
"parse" "withCallingHandlers" "suppressWarnings" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getAnywhere" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.blackListEvaluationDataTable" ".rs.blackListEvaluation" ".rs.getCompletionsSingleBracket" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"fsub" "htmlify" "Rd2HTML" "<Anonymous>" ".rs.getHelp" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"match" "%in%" "<Anonymous>" 
"isBaseNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" "lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"is.factor" "unique.default" "unique" "simplify2array" "sapply" "RdTags" "writeContent" "writeHref" "writeLink" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"f" "Reduce" "<Anonymous>" 
".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"search" "which" "get" "inherits" ".rs.getCompletionType" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "vapply" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"paste" ".rs.asCaseInsensitiveRegex" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"gettext" "sprintf" "gettextf" "stop" "find.package" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"tryCatch" ".rs.getHelp" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"FUN" "lapply" "Reduce" ".rs.getCompletionsPackages" "Reduce" "<Anonymous>" 
".rs.callsUseMethod" ".rs.callsUseMethod" ".rs.callsUseMethod" ".rs.callsUseMethod" ".rs.callsUseMethod" ".rs.callsUseMethod" ".rs.isS3Generic" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.resolveFormals" ".rs.getCompletionsFunction" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"objects" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"tryCatch" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"getFromFrame" "<Anonymous>" "lazyLoadDBfetch" "fetch" "fun" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"any" "ifelse" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"[" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"[" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"vhtmlify" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"vhtmlify" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"vhtmlify" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpArgument" "<Anonymous>" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"scan" "read.table" "read.csv" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"file.exists" "FUN" "lapply" ".rs.getCompletionsHelp" "<Anonymous>" 
"list.files" "find.package" "index.search" "help" "eval" "eval" "?" 
"is.numeric_version" ".encode_numeric_version" "Ops.numeric_version" ">=" ".rs.httpdPortIsFunction" "<Anonymous>" ".Call" "browser" "browseURL" "print.help_files_with_topic" "print" 
"match" "%in%" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"lapply" "sapply" "RdTags" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"parent.frame" "tryCatch" "FUN" "lapply" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"fsub" "htmlify" "isBlankLineRd" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"psub" "addParaBreaks" "writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"save" "<Anonymous>" 
"paste" "<Anonymous>" 
"grep" "ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"structure" ".POSIXct" "file.info" "find.package" "index.search" "help" "eval" "eval" "?" 
"readRDS" "index.search" "help" "eval" "eval" "?" 
"file.exists" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"match" "%in%" "structure" "grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"grep" "isBlankRd" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"structure" ".POSIXct" "file.info" "find.package" "index.search" "help" "eval" "eval" "?" 
"match" "%in%" "find.package" "system.file" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"paste0" "writeLines" "writeLinesUTF8" "of0" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"writeLines" "writeLinesUTF8" "of1" "writeContent" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"writeLines" "writeLinesUTF8" "of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"of1" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "try" 
"gzfile" "save" "<Anonymous>" 
"match.arg" ".geometry" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "<Anonymous>" 
".External" "<Anonymous>" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "<Anonymous>" 
"print" "eval" "eval" "withVisible" "evalVis" "capture.output" ".rs.resolveObjectFromFunctionCall" ".rs.getCompletionsArgument" ".rs.getCompletionsFunction" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"grepl" ".rs.makeCompletions" ".rs.emptyCompletions" ".rs.getCompletionsNAMESPACE" "Reduce" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"get" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match.arg" "sink" "tryCatch" ".Rd_get_text" ".Rd_get_title" "gsub" ".Rd_format_title" "strwrap" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"FUN" "vapply" "urlify" "paste0" "writeLink" "writeBlock" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" "FUN" "lapply" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"%in%" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "index.search" "<Anonymous>" "eval" "eval" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"match.fun" "lapply" "unlist" "unique" "simplify2array" "sapply" "RdTags" "writeContent" "writeWrapped" "writeBlock" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"parent.frame" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"::" "formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"readRDS" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"writeLinesUTF8" "of0" "writeWrapped" "writeBlock" "writeContent" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"simplify2array" "sapply" "RdTags" "writeContent" "writeSection" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"asNamespace" "getExportedValue" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.name" "getNamespace" "asNamespace" "getExportedValue" "::" "formals" "as.list" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"as.character" "::" "do.call" "doTryCatch" "tryCatchOne" "tryCatchList" "tryCatch" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"gzfile" "readRDS" "lazyLoadDBexec" "<Anonymous>" "<Anonymous>" "prepare_Rd" "Rd2HTML" "<Anonymous>" ".rs.getHelp" ".rs.getHelpFromObject" ".rs.getHelpFunction" "<Anonymous>" 
"ls" "FUN" "lapply" ".rs.objectsOnSearchPath" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"unlist" "simplify2array" "sapply" ".rs.resolveObjectFromFunctionCall" ".rs.getCompletionsFunction" ".rs.appendCompletions" ".rs.getRCompletions" ".rs.appendCompletions" "<Anonymous>" 
"rep.int" "FUN" "lapply" "unlist" ".rs.getCompletionsSearchPath" "Reduce" "<Anonymous>" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.character.default" "as.character" "as.character" "gsub" 
"as.chara